### ISSUE TITLE
Fault tolerance not working: "Unable to connect" causes jms exception

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#101]
If a device cannot be reached, the resulting unable to connect exception is not properly handled in osgp-core causing the fault tolerance retry mechanism will not work properly.

**Comment by smvdheijden** [comment]
Stacktrace from debug:
11:48:42.407 [New I/O boss #3] WARN  (Slf4JLogger.java:76) o.j.n.channel.DefaultChannelFuture - An exception was thrown by ChannelFutureListener.
java.io.IOException: ChannelFuture - Unable to connect
	at com.alliander.osgp.adapter.protocol.oslp.infra.networking.OslpChannelHandlerClient$1.operationComplete(OslpChannelHandlerClient.java:127) ~[OslpChannelHandlerClient$1.class:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:384) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:142) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
11:48:42.415 [New I/O boss #3] INFO  (Slf4JLogger.java:52) o.j.n.handler.logging.LoggingHandler - [id: 0x9a162fb0] EXCEPTION: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /99.99.99.99:12121
org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /99.99.99.99:12121
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:139) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
11:48:42.423 [New I/O boss #3] WARN  (OslpChannelHandler.java:103) c.a.o.a.p.o.i.n.OslpChannelHandlerClient - -1709822032 Unexpected exception from downstream. {}
org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /99.99.99.99:12121
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:139) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
11:48:42.452 [New I/O boss #3] INFO  (Slf4JLogger.java:48) o.j.n.handler.logging.LoggingHandler - [id: 0x9a162fb0] CLOSE
11:48:42.466 [DefaultMessageListenerContainer-1] INFO  (ProtocolResponseMessageListener.java:41) c.a.o.c.i.j.p.ProtocolResponseMessageListener - Received protocol response message with correlationUid [LianderNetManagement|||DVC-TST-002|||20150706114812045] and type [SET_LIGHT]
11:48:42.483 [DefaultMessageListenerContainer-1] ERROR (ProtocolResponseMessageListener.java:56) c.a.o.c.i.j.p.ProtocolResponseMessageListener - Exception: Failed to build body from content. Serializable class not available to broker. Reason: java.lang.ClassNotFoundException: org.jboss.netty.channel.ConnectTimeoutException, StackTrace: [org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36), org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:193), com.alliander.osgp.core.infra.jms.protocol.ProtocolResponseMessageListener.createResponseMessage(ProtocolResponseMessageListener.java:62), com.alliander.osgp.core.infra.jms.protocol.ProtocolResponseMessageListener.onMessage(ProtocolResponseMessageListener.java:44), org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:562), org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:500), org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:468), org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325), org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263), org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1101), org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1093), org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:990), java.lang.Thread.run(Thread.java:745)]
javax.jms.JMSException: Failed to build body from content. Serializable class not available to broker. Reason: java.lang.ClassNotFoundException: org.jboss.netty.channel.ConnectTimeoutException
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36) ~[activemq-client-5.10.0.jar:5.10.0]
	at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:193) ~[activemq-client-5.10.0.jar:5.10.0]
	at com.alliander.osgp.core.infra.jms.protocol.ProtocolResponseMessageListener.createResponseMessage(ProtocolResponseMessageListener.java:62) ~[ProtocolResponseMessageListener.class:na]
	at com.alliander.osgp.core.infra.jms.protocol.ProtocolResponseMessageListener.onMessage(ProtocolResponseMessageListener.java:44) ~[ProtocolResponseMessageListener.class:na]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:562) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:500) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:468) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1101) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1093) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:990) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.channel.ConnectTimeoutException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720) ~[catalina.jar:7.0.59]
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571) ~[catalina.jar:7.0.59]
	at java.lang.Class.forName0(Native Method) ~[na:1.7.0_79]
	at java.lang.Class.forName(Class.java:274) ~[na:1.7.0_79]
	at org.apache.activemq.util.ClassLoadingAwareObjectInputStream.load(ClassLoadingAwareObjectInputStream.java:95) ~[activemq-client-5.10.0.jar:5.10.0]
	at org.apache.activemq.util.ClassLoadingAwareObjectInputStream.resolveClass(ClassLoadingAwareObjectInputStream.java:43) ~[activemq-client-5.10.0.jar:5.10.0]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500) ~[na:1.7.0_79]
	at java.lang.Throwable.readObject(Throwable.java:914) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_79]
	at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:191) ~[activemq-client-5.10.0.jar:5.10.0]
	... 11 common frames omitted

**Comment by smvdheijden** [comment]
Possible solution: remove inner exception from message to osgp-core.

**Comment by smvdheijden** [comment]
Exception occurs if a device cannot be reached on an external ip address (for example use: 99.99.99.99)

**Comment by klvries** [comment]
I think the issue is not solved. I see this tstill this type of logging:


12:12:32.944 [DefaultMessageListenerContainer-2] ERROR (ProtocolResponseMessageListener.java:49) c.a.o.c.i.j.p.ProtocolResponseMessageListener - Exception: Failed to build body from content. Serializable class not available to broker. Reason: java.lang.ClassNotFoundException: com.alliander.osgp.adapter.protocol.oslp.exceptions.NoDeviceResponseException, StackTrace: [org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36), org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:193), com.alliander.osgp.core.infra.jms.protocol.ProtocolResponseMessageListener.createResponseMessage(ProtocolResponseMessageListener.java:55), com.alliander.osgp.core.infra.jms.protocol.ProtocolResponseMessageListener.onMessage(ProtocolResponseMessageListener.java:37), org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:562), org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:500), org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:468), org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325), org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263), org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1101), org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1093), org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:990), java.lang.Thread.run(Thread.java:744)]
javax.jms.JMSException: Failed to build body from content. Serializable class not available to broker. Reason: java.lang.ClassNotFoundException: com.alliander.osgp.adapter.protocol.oslp.exceptions.NoDeviceResponseException
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36) ~[activemq-client-5.10.0.jar:5.10.0]
        at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:193) ~[activemq-client-5.10.0.jar:5.10.0]
        at com.alliander.osgp.core.infra.jms.protocol.ProtocolResponseMessageListener.createResponseMessage(ProtocolResponseMessageListener.java:55) ~[ProtocolResponseMessageListener.class:na]
        at com.alliander.osgp.core.infra.jms.protocol.ProtocolResponseMessageListener.onMessage(ProtocolResponseMessageListener.java:37) ~[ProtocolResponseMessageListener.class:na]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:562) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:500) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:468) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1101) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1093) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:990) [spring-jms-3.2.10.RELEASE.jar:3.2.10.RELEASE]
