### ISSUE TITLE
SmartMeterMonitoring: When in the request an identifier is used that not exist a 'Nullpointer exception' is thrown

### ISSUE THREAD

**Issue by klvries** [OSGP/Platform#164]
SmartMeterMonitoring: When in the request an identifier is used that not exist a 'Nullpointer exception' is thrown.

The following logging is created:

```
09:10:24.952 [domainSmartMeteringIncomingWebServiceRequestMessageListenerContainer-2] INFO  (MonitoringService.java:62) c.a.o.a.d.s.a.s.MonitoringService - requestPeriodicMeterReads for organisationIdentification: LianderNetManagement for deviceIdentification: G14980000141227xx
09:10:25.012 [DefaultMessageListenerContainer-2] INFO  (DomainRequestMessageListener.java:48) c.a.o.c.i.j.d.DomainRequestMessageListener - Received domain request message of type: REQUEST_PERIODIC_METER_DATA for domain: SMART_METERING and domainVersion: 1.0
09:10:25.055 [DefaultMessageListenerContainer-2] WARN  (AbstractMessageListenerContainer.java:936) o.s.j.l.DefaultMessageListenerContainer - Execution of JMS message listener failed, and no ErrorHandler has been set.
java.lang.NullPointerException: null
        at com.alliander.osgp.core.application.services.DeviceRequestMessageService.processMessage(DeviceRequestMessageService.java:57) ~[DeviceRequestMessageService.class:na]
        at com.alliander.osgp.core.application.services.DeviceRequestMessageService$$FastClassBySpringCGLIB$$5aec3c42.invoke(<generated>) ~[spring-core-4.2.0.RELEASE.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at com.alliander.osgp.core.application.services.DeviceRequestMessageService$$EnhancerBySpringCGLIB$$a42c2639.processMessage(<generated>) ~[spring-core-4.2.0.RELEASE.jar:na]
        at com.alliander.osgp.core.infra.jms.domain.DomainRequestMessageListener.onMessage(DomainRequestMessageListener.java:58) ~[DomainRequestMessageListener.class:na]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746) ~[spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684) ~[spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651) ~[spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_55]
09:10:25.153 [DefaultMessageListenerContainer-2] INFO  (DomainRequestMessageListener.java:48) c.a.o.c.i.j.d.DomainRequestMessageListener - Received domain request message of type: REQUEST_PERIODIC_METER_DATA for domain: SMART_METERING and domainVersion: 1.0
09:10:25.182 [DefaultMessageListenerContainer-2] WARN  (AbstractMessageListenerContainer.java:936) o.s.j.l.DefaultMessageListenerContainer - Execution of JMS message listener failed, and no ErrorHandler has been set.
```

**Comment by rlemmers** [comment]
Check #164, because it might be related.

**Comment by bvdzwet** [comment]
Relates to #168 and #173.

**Comment by klvries** [comment]
Now the service logs:

```
13:49:51.624 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (FindEventsResponseMessageProcessor.java:84) c.a.o.a.w.s.i.j.m.FindEventsResponseMessageProcessor - Calling application service function to handle response: FIND_EVENTS
13:49:51.625 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (DomainResponseMessageProcessor.java:90) c.a.o.a.w.s.i.j.m.DomainResponseMessageProcessor - handeling error: null for notification type: FIND_EVENTS
13:49:51.628 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (NotificationService.java:47) c.a.o.a.w.s.a.s.NotificationService - sendNotification called with organisation LianderNetManagement
13:49:51.736 [ajp-bio-8009-exec-63] INFO  (SmartMeteringNotificationEndpoint.java:42) c.a.o.s.w.i.w.e.SmartMeteringNotificationEndpoint - Incoming SendNotificationRequest for organisation: LianderNetManagement device: E999800001412271a.
13:49:51.737 [ajp-bio-8009-exec-63] INFO  (NotificationService.java:40) c.a.o.s.w.a.s.NotificationService - Incoming Notification of type: FIND_EVENTS with result: NOT_OK
13:49:51.737 [ajp-bio-8009-exec-63] INFO  (ManagementService.java:65) c.a.o.s.w.a.s.ManagementService - handleFindEvents called with organisationIdentification: LianderNetManagement, deviceIdentification: E999800001412271a, correlationUid: LianderNetManagement|||E999800001412271a|||20151026134951247
13:49:51.832 [ajp-bio-8009-exec-9] INFO  (SmartMeteringManagementEndpoint.java:105) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - Get find events response for organisation: LianderNetManagement and device: E999800001412271a.
13:49:51.834 [ajp-bio-8009-exec-9] INFO  (ManagementService.java:97) c.a.o.a.w.s.a.s.ManagementService - findEventsByCorrelationUid called with organisation LianderNetManagement}
13:49:51.840 [ajp-bio-8009-exec-9] INFO  (ManagementService.java:118) c.a.o.a.w.s.a.s.ManagementService - deleting 0 MeterResponseData rows
13:49:51.841 [ajp-bio-8009-exec-9] INFO  (ManagementService.java:121) c.a.o.a.w.s.a.s.ManagementService - returning a list containing 0 events
13:49:51.842 [ajp-bio-8009-exec-9] INFO  (SmartMeteringManagementEndpoint.java:119) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - getFindEventsResponse() number of events: 0
13:49:51.842 [ajp-bio-8009-exec-9] INFO  (SmartMeteringManagementEndpoint.java:123) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping events to schema type...
13:49:51.843 [ajp-bio-8009-exec-9] INFO  (SmartMeteringManagementEndpoint.java:127) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping done, sending response...
13:49:51.863 [ajp-bio-8009-exec-63] INFO  (ManagementService.java:75) c.a.o.s.w.a.s.ManagementService - handleFindEvents received 0 events:
 ```
