### ISSUE TITLE
RetrievePeriodicMeterReads: nullpointer exception when trying to retrieve a result what does not exist

### ISSUE THREAD

**Issue by klvries** [OSGP/Platform#168]
RequestPeriodicMeterReads: nullpointer exception when trying to request the reads from a device what does not exist.

In the 'FindEventResponse' this works fine.
No nullpointer eception in the logging. It should work like this component.

```
09:05:25.928 [ajp-bio-8009-exec-13] INFO  (SmartMeteringManagementEndpoint.java:105) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - Get find events response for organisation: LianderNetManagement and device: E9998000014122716.
09:05:25.956 [ajp-bio-8009-exec-13] INFO  (ManagementService.java:97) c.a.o.a.w.s.a.s.ManagementService - findEventsByCorrelationUid called with organisation LianderNetManagement}
09:05:26.097 [ajp-bio-8009-exec-13] INFO  (ManagementService.java:118) c.a.o.a.w.s.a.s.ManagementService - deleting 0 MeterResponseData rows
09:05:26.099 [ajp-bio-8009-exec-13] INFO  (ManagementService.java:121) c.a.o.a.w.s.a.s.ManagementService - returning a list containing 0 events
09:05:26.101 [ajp-bio-8009-exec-13] INFO  (SmartMeteringManagementEndpoint.java:119) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - getFindEventsResponse() number of events: 0
09:05:26.102 [ajp-bio-8009-exec-13] INFO  (SmartMeteringManagementEndpoint.java:123) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping events to schema type...
09:05:26.102 [ajp-bio-8009-exec-13] INFO  (SmartMeteringManagementEndpoint.java:127) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping done, sending response...
09:05:38.969 [ajp-bio-8009-exec-14] INFO  (SmartMeteringMonitoringEndpoint.java:92) c.a.o.a.w.s.e.SmartMeteringMonitoringEndpoint - Incoming RetrievePeriodicMeterReadsRequest for meter: E9998000014122721.
09:05:38.973 [ajp-bio-8009-exec-14] ERROR (SmartMeteringMonitoringEndpoint.java:111) c.a.o.a.w.s.e.SmartMeteringMonitoringEndpoint - Exception: [null, E9998000014122721, LianderNetManagement] while sending Periodic MeterReads of device: {} for organisation {}.
java.lang.NullPointerException: null
        at com.alliander.osgp.adapter.ws.smartmetering.endpoints.SmartMeteringMonitoringEndpoint.requestPeriodicData(SmartMeteringMonitoringEndpoint.java:107) ~[SmartMeteringMonitoringEndpoint.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
        at org.springframework.ws.server.endpoint.MethodEndpoint.invoke(MethodEndpoint.java:134) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.server.endpoint.adapter.DefaultMethodEndpointAdapter.invokeInternal(DefaultMethodEndpointAdapter.java:291) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.server.endpoint.adapter.AbstractMethodEndpointAdapter.invoke(AbstractMethodEndpointAdapter.java:55) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.server.MessageDispatcher.dispatch(MessageDispatcher.java:236) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.server.MessageDispatcher.receive(MessageDispatcher.java:176) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.transport.support.WebServiceMessageReceiverObjectSupport.handleConnection(WebServiceMessageReceiverObjectSupport.java:89) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.transport.http.WebServiceMessageReceiverHandlerAdapter.handle(WebServiceMessageReceiverHandlerAdapter.java:61) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.transport.http.MessageDispatcherServlet.doService(MessageDispatcherServlet.java:293) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [tomcat7-servlet-3.0-api-7.0.54.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [tomcat7-servlet-3.0-api-7.0.54.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina-7.0.54.jar:7.0.54]
        at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38) [tomcat70adaptor-2.3.2.jar:2.3.2]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina-7.0.54.jar:7.0.54]
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193) [tomcat-coyote-7.0.54.jar:7.0.54]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-coyote-7.0.54.jar:7.0.54]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-coyote-7.0.54.jar:7.0.54]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_55]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_55]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote-7.0.54.jar:7.0.54]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_55]
09:05:38.974 [ajp-bio-8009-exec-14] ERROR (SmartMeteringMonitoringEndpoint.java:128) c.a.o.a.w.s.e.SmartMeteringMonitoringEndpoint - Exception occurred:
java.lang.NullPointerException: null
        at com.alliander.osgp.adapter.ws.smartmetering.endpoints.SmartMeteringMonitoringEndpoint.requestPeriodicData(SmartMeteringMonitoringEndpoint.java:107) ~[SmartMeteringMonitoringEndpoint.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
        at org.springframework.ws.server.endpoint.MethodEndpoint.invoke(MethodEndpoint.java:134) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.server.endpoint.adapter.DefaultMethodEndpointAdapter.invokeInternal(DefaultMethodEndpointAdapter.java:291) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.server.endpoint.adapter.AbstractMethodEndpointAdapter.invoke(AbstractMethodEndpointAdapter.java:55) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.server.MessageDispatcher.dispatch(MessageDispatcher.java:236) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.server.MessageDispatcher.receive(MessageDispatcher.java:176) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.transport.support.WebServiceMessageReceiverObjectSupport.handleConnection(WebServiceMessageReceiverObjectSupport.java:89) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.transport.http.WebServiceMessageReceiverHandlerAdapter.handle(WebServiceMessageReceiverHandlerAdapter.java:61) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.transport.http.MessageDispatcherServlet.doService(MessageDispatcherServlet.java:293) [spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [tomcat7-servlet-3.0-api-7.0.54.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [tomcat7-servlet-3.0-api-7.0.54.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina-7.0.54.jar:7.0.54]
        at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38) [tomcat70adaptor-2.3.2.jar:2.3.2]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina-7.0.54.jar:7.0.54]
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193) [tomcat-coyote-7.0.54.jar:7.0.54]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-coyote-7.0.54.jar:7.0.54]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-coyote-7.0.54.jar:7.0.54]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_55]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_55]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote-7.0.54.jar:7.0.54]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_55]
```

**Comment by klvries** [comment]
Also the Retrieve requests for all smartmeter get an invalid response when trying to retrieve the response for a correlationUid what does not exist.
'''
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <ns2:RetrievePeriodicMeterReadsResponse xmlns:ns2="http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10" xmlns:ns3="http://www.alliander.com/schemas/osgp/common/2014/10"/>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
````
line 4: Expected element 'PeriodicMeterReadsContainer@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' before the end of the content in element RetrievePeriodicMeterReadsResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10
```

**Comment by bvdzwet** [comment]
Before finishing this fix, I would like to discuss handling of exceptions in the flow from web service adapters to the core or protocol adapters and back, and the way exceptions are dealt with in the notification handling (not ok notifications).

With regards to exceptions in the message flow look e.g. in Platform project osgp-adapter-domain-smartmetering at the OsgpCoreResponseMessageProcessor in package com.alliander.osgp.adapter.domain.smartmetering.infra.jms.core.
This has a method handleError where a ResponseMessage is constructed for the exception that occurred.
The exception in this method ends up in the dataObject of the response message, while a TechnicalException wrapping the exception that occurred is created to be inserted as the osgpException object in the response message.
My first question is: do we want the dataObject to contain an exception in certain cases, or should it be null if an exception occurred when no actual response data is available?
My second question is: if the exception that is handled already is an OsgpException, do we want to wrap it in a TechnicalException, or do we want to place it as is, as the osgpException in the response message?

**Comment by bvdzwet** [comment]
Smart metering domain application services in osgp-adapter-domain-smartmetering should reflect changes based on discussion about the questions raised in the previous comment.

**Comment by klvries** [comment]
The issue is solved.

Now the service logs:

```
13:49:51.624 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (FindEventsResponseMessageProcessor.java:84) c.a.o.a.w.s.i.j.m.FindEventsResponseMessageProcessor - Calling application service function to handle response: FIND_EVENTS
13:49:51.625 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (DomainResponseMessageProcessor.java:90) c.a.o.a.w.s.i.j.m.DomainResponseMessageProcessor - handeling error: null for notification type: FIND_EVENTS
13:49:51.628 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (NotificationService.java:47) c.a.o.a.w.s.a.s.NotificationService - sendNotification called with organisation LianderNetManagement
13:49:51.736 [ajp-bio-8009-exec-63] INFO  (SmartMeteringNotificationEndpoint.java:42) c.a.o.s.w.i.w.e.SmartMeteringNotificationEndpoint - Incoming SendNotificationRequest for organisation: LianderNetManagement device: E999800001412271a.
13:49:51.737 [ajp-bio-8009-exec-63] INFO  (NotificationService.java:40) c.a.o.s.w.a.s.NotificationService - Incoming Notification of type: FIND_EVENTS with result: NOT_OK
13:49:51.737 [ajp-bio-8009-exec-63] INFO  (ManagementService.java:65) c.a.o.s.w.a.s.ManagementService - handleFindEvents called with organisationIdentification: LianderNetManagement, deviceIdentification: E999800001412271a, correlationUid: LianderNetManagement|||E999800001412271a|||20151026134951247
13:49:51.832 [ajp-bio-8009-exec-9] INFO  (SmartMeteringManagementEndpoint.java:105) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - Get find events response for organisation: LianderNetManagement and device: E999800001412271a.
13:49:51.834 [ajp-bio-8009-exec-9] INFO  (ManagementService.java:97) c.a.o.a.w.s.a.s.ManagementService - findEventsByCorrelationUid called with organisation LianderNetManagement}
13:49:51.840 [ajp-bio-8009-exec-9] INFO  (ManagementService.java:118) c.a.o.a.w.s.a.s.ManagementService - deleting 0 MeterResponseData rows
13:49:51.841 [ajp-bio-8009-exec-9] INFO  (ManagementService.java:121) c.a.o.a.w.s.a.s.ManagementService - returning a list containing 0 events
13:49:51.842 [ajp-bio-8009-exec-9] INFO  (SmartMeteringManagementEndpoint.java:119) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - getFindEventsResponse() number of events: 0
13:49:51.842 [ajp-bio-8009-exec-9] INFO  (SmartMeteringManagementEndpoint.java:123) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping events to schema type...
13:49:51.843 [ajp-bio-8009-exec-9] INFO  (SmartMeteringManagementEndpoint.java:127) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping done, sending response...
13:49:51.863 [ajp-bio-8009-exec-63] INFO  (ManagementService.java:75) c.a.o.s.w.a.s.ManagementService - handleFindEvents received 0 events:
```
