### ISSUE TITLE
smartmeter-demo-applicatie: the notification does not work via the smart-meter-demo application

### ISSUE THREAD

**Issue by klvries** [OSGP/Platform#175]
smartmeter-demo-applicatie: the notification does not work via the smart-meter-demo application due to the fact that the application does not work correct with https

```
Request's attribute was not an array of X509Certificates.
11:53:06.049 [ajp-bio-8009-exec-25] WARN  (CertificateAndSoapHeaderAuthorizationEndpointInterceptor.java:51) c.a.o.a.w.e.CertificateAndSoapHeaderAuthorizationEndpointInterceptor - Soapheader or CN is empty.
11:53:06.058 [wsSmartMeteringResponsesMessageListenerContainer-1] ERROR (NotificationService.java:61) c.a.o.a.w.s.a.s.NotificationService - Notification exception
org.springframework.ws.soap.client.SoapFaultClientException: Client certificate is untrusted or invalid for organisation [LianderNetManagement]
        at org.springframework.ws.soap.client.core.SoapFaultMessageResolver.resolveFault(SoapFaultMessageResolver.java:38) ~[spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.client.core.WebServiceTemplate.handleFault(WebServiceTemplate.java:826) ~[spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:621) ~[spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555) ~[spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390) ~[spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:383) ~[spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:373) ~[spring-ws-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
        at com.alliander.osgp.adapter.ws.smartmetering.infra.ws.SendNotificationServiceClient.sendNotification(SendNotificationServiceClient.java:44) ~[SendNotificationServiceClient.class:na]
        at com.alliander.osgp.adapter.ws.smartmetering.application.services.NotificationService.sendNotification(NotificationService.java:58) ~[NotificationService.class:na]
        at com.alliander.osgp.adapter.ws.smartmetering.application.services.NotificationService$$FastClassBySpringCGLIB$$4f9b1f15.invoke(<generated>) [spring-core-4.2.0.RELEASE.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.validation.beanvalidation.MethodValidationInterceptor$HibernateValidatorDelegate.invokeWithinValidation(MethodValidationInterceptor.java:173) [spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:132) [spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) [spring-tx-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) [spring-tx-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at com.alliander.osgp.adapter.ws.smartmetering.application.services.NotificationService$$EnhancerBySpringCGLIB$$b24d98e8.sendNotification(<generated>) [spring-core-4.2.0.RELEASE.jar:na]
        at com.alliander.osgp.adapter.ws.smartmetering.infra.jms.messageprocessor.PeriodicMeterReadsresponseMessageProcessor.processMessage(PeriodicMeterReadsresponseMessageProcessor.java:94) [PeriodicMeterReadsresponseMessageProcessor.class:na]
        at com.alliander.osgp.adapter.ws.smartmetering.infra.jms.SmartMeteringResponseMessageListener.onMessage(SmartMeteringResponseMessageListener.java:64) [SmartMeteringResponseMessageListener.class:na]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039) [spring-jms-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_55]
11:53:09.091 [http-bio-8080-exec-2] INFO  (AbstractLoggingInterceptor.java:250) o.a.c.i.LoggingInInterceptor - Inbound Message
```

**Comment by smvdheijden** [comment]
Issue logged in wrong repo
