### ISSUE TITLE
Requested meter read leads to angularjs error

### ISSUE THREAD

**Issue by SCMHaime** [OSGP/Platform#258]
When requesting meter reads an angularjs error pops up when debugging the smartmeter app (by using for example the F12 Developer Tools, IE). 

This is an example of the displayed error:

Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.2.6/$rootScope/inprog?p0=%24digest
   at beginPhase (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:27913)
   at Scope.prototype.$apply (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:8:1200)
   at addNotification (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:24262)
   at notificationsService.pushForCurrentRoute (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:25030)
   at I18nNotifications.pushForCurrentRoute (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:20595)
   at Anonymous function (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:21106)
   at wrappedCallback (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:24682)
   at Anonymous function (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:26093)
   at Scope.prototype.$eval (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:8:868)
   at Scope.prototype.$digest (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:31039)
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: web-smartmeter-demo
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.2.6/$rootScope/inprog?p0=%24digest
   at beginPhase (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:27913)
   at Scope.prototype.$apply (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:8:1200)
   at addNotification (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:24262)
   at notificationsService.pushForCurrentRoute (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:25030)
   at I18nNotifications.pushForCurrentRoute (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:20595)
   at Anonymous function (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:21106)
   at wrappedCallback (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:24682)
   at Anonymous function (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:26093)
   at Scope.prototype.$eval (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:8:868)
   at Scope.prototype.$digest (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:31039)
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.2.6/$rootScope/inprog?p0=%24digest
   at beginPhase (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:27913)
   at Scope.prototype.$apply (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:8:1200)
   at addNotification (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:24262)
   at notificationsService.pushForCurrentRoute (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:25030)
   at I18nNotifications.pushForCurrentRoute (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:20595)
   at Anonymous function (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/fa90e789.scripts.js:1:21106)
   at wrappedCallback (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:24682)
   at Anonymous function (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:26093)
   at Scope.prototype.$eval (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:8:868)
   at Scope.prototype.$digest (https://osgp-tst.cloudapp.net:62443/web-smartmeter-demo/scripts/95579205.vendor.js:7:31039)

**Comment by rudidevries** [comment]
This issue has been fixed. Will be applied with the changes of the AMR profile git-branche.

Connects to SmartSocietyServices/Webapps#239
