### ISSUE TITLE
web-net-management: the plotter function on the 'schakelhistorie' page is not always correct

### ISSUE THREAD

**Issue by klvries** [OSGP/Platform#44]
When there is a switch off event, and the light was already turned off, it seems that the light was on previous to the event.

**Comment by klvries** [comment]
The plotterfunctionality is still not correct.

When the devce is on at the end of the previous day it seems that the plotter function not looks correct to the previous event.

**Comment by klvries** [comment]
Besides this there is an error with a nullpointer exception for relais 3 :

14:10:38.373 [ajp-bio-8009-exec-198] INFO  (LoggingMessageSender.java:53) c.a.o.a.w.i.jms.LoggingMessageSender - Sending logger message to queue
14:10:38.400 [ajp-bio-8009-exec-190] INFO  (DeviceManagementService.java:316) c.a.o.n.a.s.DeviceManagementService - filter events
14:10:38.401 [ajp-bio-8009-exec-190] INFO  (DeviceManagementService.java:361) c.a.o.n.a.s.DeviceManagementService - eventsOfDayBefore is empy
14:10:38.401 [ajp-bio-8009-exec-190] INFO  (DeviceManagementService.java:369) c.a.o.n.a.s.DeviceManagementService - creating initial event for relay index: 3
14:10:38.404 [ajp-bio-8009-exec-190] ERROR (DevicesResource.java:327) c.a.o.n.api.DevicesResource - get switching history exception
java.lang.NullPointerException: null
        at com.alliander.osgp.netmanagementweb.application.services.DeviceManagementService.checkIfInitialEventsArePresent(DeviceManagementService.java:374) ~[DeviceManagementService.class:na]
        at com.alliander.osgp.netmanagementweb.application.services.DeviceManagementService.filterEvents(DeviceManagementService.java:327) ~[DeviceManagementService.class:na]
        at com.alliander.osgp.netmanagementweb.application.services.DeviceManagementService.publicLightingHistory(DeviceManagementService.java:271) ~[DeviceManagementService.class:na]
        at com.alliander.osgp.netmanagementweb.application.services.DeviceManagementService$$FastClassBySpringCGLIB$$a97145a2.invoke(<generated>) ~[spring-core-3.2.10.RELEASE.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700) ~[spring-aop-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633) ~[spring-aop-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at com.alliander.osgp.netmanagementweb.application.services.DeviceManagementService$$EnhancerBySpringCGLIB$$dbf1b630.publicLightingHistory(<generated>) ~[spring-core-3.2.10.RELEASE.jar:na]
        at com.alliander.osgp.netmanagementweb.api.DevicesResource.getPublicLightingSwitchingHistory(DevicesResource.java:322) ~[DevicesResource.class:na]
        at sun.reflect.GeneratedMethodAccessor1583.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181) [cxf-core-3.0.1.jar:3.0.1]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97) [cxf-core-3.0.1.jar:3.0.1]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200) [cxf-rt-frontend-jaxrs-3.0.1.jar:3.0.1]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99) [cxf-rt-frontend-jaxrs-3.0.1.jar:3.0.1]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.0.1.jar:3.0.1]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.0.1.jar:3.0.1]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.0.1.jar:3.0.1]
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.0.1.jar:3.0.1]
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:243) [cxf-rt-transports-http-3.0.1.jar:3.0.1]
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223) [cxf-rt-transports-http-3.0.1.jar:3.0.1]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:197) [cxf-rt-transports-http-3.0.1.jar:3.0.1]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:149) [cxf-rt-transports-http-3.0.1.jar:3.0.1]
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171) [cxf-rt-transports-http-3.0.1.jar:3.0.1]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286) [cxf-rt-transports-http-3.0.1.jar:3.0.1]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:211) [cxf-rt-transports-http-3.0.1.jar:3.0.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620) [tomcat7-servlet-3.0-api-7.0.54.jar:na]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:262) [cxf-rt-transports-http-3.0.1.jar:3.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina-7.0.54.jar:7.0.54]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at com.alliander.osgp.shared.security.AuthenticationTokenProcessingFilter.doFilter(AuthenticationTokenProcessingFilter.java:81) [shared-0.11.0-SNAPSHOT.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106) [spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343) [spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260) [spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina-7.0.54.jar:7.0.54]
        at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38) [tomcat70adaptor-2.3.2.jar:2.3.2]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina-7.0.54.jar:7.0.54]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina-7.0.54.jar:7.0.54]
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193) [tomcat-coyote-7.0.54.jar:7.0.54]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-coyote-7.0.54.jar:7.0.54]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-coyote-7.0.54.jar:7.0.54]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_55]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_55]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote-7.0.54.jar:7.0.54]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_55]
14:10:38.407 [ajp-bio-8009-exec-190] INFO  (AbstractLoggingInterceptor.java:250) o.a.c.i.LoggingOutInterceptor - Outbound Message
---------------------------
ID: 846
Response-Code: 400
Content-Type: application/json
Headers: {Content-Type=[application/json], Date=[Mon, 20 Jul 2015 14:10:38 GMT], Cache-Control=[no-cache,no-store,no-transform,must-revalidate,s-maxage=0]}
Payload: {"errorMessage":null}
--------------------------------------
14:10:38.425 [loggingMessageListenerContainer-3] INFO  (LoggingMessageListener.java:43) c.a.o.l.i.jms.LoggingMessageListener - Received logging message
14:13:35.946 [pool-16-thread-1] INFO  (DeviceMonitoringService.java:162) c.a.o.n.a.s.DeviceMonitoringService - Check for power usage data for all devices in a month from 2015-05-31T00:00:00.000Z untill 2015-06-30T00:00:00.000Z .
14:15:00.000 [osgp-core-scheduling-1] INFO  (ScheduledTaskScheduler.java:44) c.a.o.c.a.t.ScheduledTaskScheduler - Processing scheduled tasks
